Controller:
  model_structure: null
ReinforcementTrainer:
  controller_learning_rate: 0.1
  controller_optimizer: SGD
  distill_mode: false
  optimizer: SGD
  sentence_level_batch: true
embeddings:
  FastCharacterEmbeddings:
    char_embedding_dim: 25
    hidden_size_char: 25
#  ELMoEmbeddings-0:
#    model: original
  FastWordEmbeddings-0:
    embeddings: glove
    freeze: true
interpolation: 0.5
model:
  TransE:
    dropout: 0.0
    hidden_size: 800
    sentence_loss: true
model_name: fb15k_237_simple_model
kgc:
  Corpus: FB15K_237
#  tag_dictionary: resources/taggers/ner_tags.pkl
target_dir: resources/taggers/
targets: kgc
train:
  controller_momentum: 0.9
  discount: 0.5
  learning_rate: 0.1
  max_episodes: 10
  max_epochs: 10
  max_epochs_without_improvement: 2
  mini_batch_size: 32
  monitor_test: false
  patience: 5
  save_final_model: false
  train_with_dev: false
  true_reshuffle: false
trainer: ReinforcementTrainer

#ast:
#  Corpus: SEMEVAL16-TR:SEMEVAL16-ES:SEMEVAL16-NL:SEMEVAL16-EN:SEMEVAL16-RU
#atis:
#  Corpus: ATIS-EN:ATIS-TR:ATIS-HI
#chunk:
#  Corpus: CONLL_03:CONLL_03_GERMAN